apiVersion: v1
kind: Secret
metadata:
  name: springboot-secrets
type: Opaque
stringData:
  mail-usuari: "tu-email@gmail.com"  # Cambia esto por tu email
  mail-contra: "tu-password-app"     # Cambia esto por tu contraseña de aplicación

